### ISSUE TITLE
main slider

### ISSUE THREAD

**Issue by jiji-hoon96** [HealthCommunity/frontend#47]
![image](https://user-images.githubusercontent.com/94469974/178419460-cba0afbd-2162-4555-919e-388bc7340561.png)

arrow가 슬라이더 겹치게보입니다!

arrow 범위 안쪽까지만 슬라이더를 보이게하는게 어떨까싶어요!

**Comment by pasong0511** [comment]
width: 90%로 감소, swipper 라이브리의 커스텀의 어려움으로 버튼을 부각시키도록 모형 변경
