### ISSUE TITLE
[Question] Components 와 FuncSkills 구분논의

### ISSUE THREAD

**Issue by jiji-hoon96** [HealthCommunity/frontend#8]
![image](https://user-images.githubusercontent.com/94469974/177079295-8c2f5f66-631d-4694-96bd-d7736bf6fe1c.png)

제가 임의로 각 components를 구분해보았습니다.
1. Components의 하단에 있는 Board, Footer, Main(Home),Navigation 등등으로 나누었습니다

- 차후 Board 부분을 각각 게시판에 맞춰 분리할 예정입니다
- Main이라고 지은이유는 Home이라고 하면 Routes와 겹쳐서 변경했습니다
- Footer와 Navigation은  각각 style/logic 으로 구분했습니다

> (이렇게 변경한 이유는 각 Routes 성격에 맞게 폴더에서 각각 처리해야 수정할때 찾기 쉬울거같아서 했습니다)

2. Funcskills 는 문법적, 배열, 비동기처리를 하면거같습니다

- 만들어주신 useForm이 적합한 FuncSkills 같습니다!!

3. FakeD는 차후 APIDATA로 폴더를 변경해서 각 데이터를 처리하면 될거같습니다.
 
- 중복된 API를 사용할 경우 =>  지금 FakeD 위치에서 처리해서 export 하면될거같습니다
- 게시판에 한번 render 해야하는 API를 사용할 경우 => 해당폴더에서 useEffect를 이용해 한번 처리해 해당 폴더에서만 관리하는 방식이 좋지 않을까 싶습니다. 

> 고치다보니 만들어주신 login, sign ,profile 에 import 경로가 변경되어있어서 말씀드려요
> 깔끔하게 분리시켜놓고 앞으로 작업할려고하다보니 많이 변경되었습니다. 
> 제가 마음대로 고쳐놔서 죄송합니다. 
> 확인해보시고 변경이 필요하면 comment 부탁드릴게요.
> pr은 comment 확인하고 하겠습니다
> 이해안되거나 많은 변경이 필요할 경우 Comment와 함께 Discord에서 변경해보면 좋을거같습니다!

**Comment by pasong0511** [comment]
넵넵 경로 변경 좋습니다.
pr 올려주시면 맞춰서 작업하도록 하겠습니다!

**Comment by jiji-hoon96** [comment]
pr 하겠습니다~!
